---
- name: Check if impacket is installed
  ansible.builtin.stat:
    path: "{{ local_bin }}/bloodhound-python"
  register: bloodhound_stat

- name: Install impacket via uv
  when: not bloodhound_stat.stat.exists
  ansible.builtin.shell: uv tool install bloodhound
  args:
    executable: /bin/bash
