---
- name: Clone pentest tools into ~/opt
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ user_home }}/opt/{{ item.name }}"
    depth: 1
    update: true
  loop: "{{ pentest_tools }}"
  ignore_errors: true
