---
- name: Check if donut binary exists
  ansible.builtin.stat:
    path: "{{ user_home }}/opt/donut/donut"
  register: donut_stat

- name: Install donut build dependencies
  become: true
  when: not donut_stat.stat.exists
  ansible.builtin.apt:
    name:
      - gcc
      - make
      - mingw-w64
      - libssl-dev
      - zlib1g-dev
    state: present
    update_cache: yes

- name: Clone donut
  when: not donut_stat.stat.exists
  ansible.builtin.git:
    repo: "https://github.com/TheWover/donut.git"
    dest: "{{ user_home }}/opt/donut"
    depth: 1

- name: Build donut
  when: not donut_stat.stat.exists
  ansible.builtin.command:
    cmd: make
    chdir: "{{ user_home }}/opt/donut"
