---
- name: Install gdb
  become: true
  ansible.builtin.apt:
    name: gdb
    state: present

- name: Clone peda into ~/peda
  ansible.builtin.git:
    repo: "https://github.com/longld/peda.git"
    dest: "{{ user_home }}/peda"
    depth: 1
    update: true

- name: Source peda in ~/.gdbinit
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.gdbinit"
    line: "source ~/peda/peda.py"
    create: true
    state: present
    mode: "0644"
