---
- import_tasks: dirs.yml
- import_tasks: clone.yml
- import_tasks: rustscan.yml
- import_tasks: feroxbuster.yml
- import_tasks: tldr.yml
- import_tasks: golang.yml
- import_tasks: ligolo.yml
- import_tasks: subfinder.yml
- import_tasks: dnscat2.yml
