---
- import_tasks: dirs.yml
  tags: dirs
- import_tasks: clone.yml
  tags: clone
- import_tasks: rustscan.yml
  tags: rustscan
- import_tasks: feroxbuster.yml
  tags: feroxbuster
- import_tasks: golang.yml
  tags: golang
- import_tasks: udpx.yml
  tags: udpx
- import_tasks: ligolo.yml
  tags: ligolo
- import_tasks: subfinder.yml
  tags: subfinder
- import_tasks: dnscat2.yml
  tags: dnscat2
- import_tasks: kerbrute.yml
  tags: kerbrute
- import_tasks: mimikatz.yml
  tags: mimikatz
- import_tasks: rubeus.yml
  tags: rubeus
- import_tasks: chisel.yml
  tags: chisel
- import_tasks: bloodhound.yml
  tags: bloodhound
- import_tasks: rusthound-ce.yml
  tags: rusthound-ce
- import_tasks: curlie.yml
  tags: curlie
- import_tasks: posting.yml
  tags: posting
- import_tasks: bloodyad.yml
  tags: bloodyad
- import_tasks: impacket.yml
  tags: impacket
- import_tasks: lfi-wordlists.yml
  tags: wordlists
- import_tasks: eyewitness.yml
  tags: eyewitness
- import_tasks: sliver.yml
  tags: sliver
- import_tasks: donut.yml
  tags: donut
- import_tasks: shortscan.yml
  tags: shortscan
- import_tasks: gdb-pwndbg.yml
  tags: gdb-pwndbg
- import_tasks: dotnet.yml
  tags: dotnet
- import_tasks: tldr.yml
  tags: tldr
