---
- name: Check if udpx is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/go/bin/udpx"
  register: udpx_stat

- name: Install udpx via go install
  when: not udpx_stat.stat.exists
  ansible.builtin.command: /usr/local/go/bin/go install -v github.com/nullt3r/udpx/cmd/udpx@latest
  environment:
    HOME: "{{ ansible_env.HOME }}"
    GOPATH: "{{ ansible_env.HOME }}/go"
